vsync = true

[font]
hinting = "full"
size = 12
edging = "antialias"

[font.features]
"MonoLisa" = [
  "+ss01",
  "+ss07",
  "+ss11",
  "+liga",
  "+calt",
  "+zero",
  "+ss09",
  "+ss02",
  "+ss14",
]

[[font.normal]]
family = "DankMono Nerd Font"
style = "Light"

# Fallback font
[[font.normal]]
family = "Symbols Nerd Font Mono"

# Fallback font (Persian font support)
[[font.normal]]
family = "Vazirmatn"

[[font.italic]]
family = "DankMono Nerd Font"

# [[font.bold]]
# family = "MonoLisa"
# style = "Semi-Bold"

# [[font.bold_italic]]
# family = "MonoLisa"
# style = "Semi-Bold Italic"

[box-drawing]
mode = "native"
