general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "DankMono Nerd Font"}
bold = { family = "DankMono Nerd Font"}
italic = { family = "DankMono Nerd Font" }
size = 14

[window]
# padding.x = 14
# padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
